// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_Wilcoxon_PermTest
List rcpp_Wilcoxon_PermTest(NumericVector X, IntegerVector Y, IntegerVector B, IntegerVector DoWald, IntegerVector ReportPerm);
RcppExport SEXP _subzero_rcpp_Wilcoxon_PermTest(SEXP XSEXP, SEXP YSEXP, SEXP BSEXP, SEXP DoWaldSEXP, SEXP ReportPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type DoWald(DoWaldSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ReportPerm(ReportPermSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Wilcoxon_PermTest(X, Y, B, DoWald, ReportPerm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Wilcoxon_PermTest_Given_Permutations
List rcpp_Wilcoxon_PermTest_Given_Permutations(NumericVector X, IntegerMatrix Y);
RcppExport SEXP _subzero_rcpp_Wilcoxon_PermTest_Given_Permutations(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Wilcoxon_PermTest_Given_Permutations(X, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subzero_rcpp_Wilcoxon_PermTest", (DL_FUNC) &_subzero_rcpp_Wilcoxon_PermTest, 5},
    {"_subzero_rcpp_Wilcoxon_PermTest_Given_Permutations", (DL_FUNC) &_subzero_rcpp_Wilcoxon_PermTest_Given_Permutations, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_subzero(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
