install.packages('Rcpp')
install.packages('ggplot2')
install.packages('BiocManager')
library(BiocManager)
BiocManager::install(c('BiocParallel', 'GenomicRanges', 'SummarizedExperiment'))
install.packages("~/CompositionalAnalysis_CodeBase/Packages/ALDEx2_1.16.0.tar.gz", repos = NULL, type = "source")
install.packages(c('exactRankTests','openxlsx'))
install.packages('coin')
install.packages("~/CompositionalAnalysis_CodeBase/Packages/ancom.R_1.1-3.tar.gz", repos = NULL, type = "source")
install.packages("~/CompositionalAnalysis_CodeBase/Packages/dacomp_1.1.tar.gz", repos = NULL, type = "source")
install.packages(c('locfit','Hmisc','RcppArmadillo'))
BiocManager::install(c('genefilter','geneplotter'))
install.packages("~/CompositionalAnalysis_CodeBase/Packages/DESeq2_1.24.0.tar.gz", repos = NULL, type = "source")
install.packages(c('glmnet','gplots'))
BiocManager::install('limma')
install.packages("~/CompositionalAnalysis_CodeBase/Packages/metagenomeSeq_1.24.1.tar.gz", repos = NULL, type = "source")
install.packages("~/CompositionalAnalysis_CodeBase/Packages/phyloseq_1.26.1.tar.gz", repos = NULL, type = "source")
install.packages("~/CompositionalAnalysis_CodeBase/Packages/subzero_1.0.tar.gz", repos = NULL, type = "source")
install.packages("~/CompositionalAnalysis_CodeBase/Packages/Wrench_1.2.0.tar.gz", repos = NULL, type = "source")
BiocManager::install('vegan')
BiocManager::install('dada2')
